/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BridgeStub {
  export type RedemptionRequestStruct = {
    redeemer: AddressLike;
    requestedAmount: BigNumberish;
    treasuryFee: BigNumberish;
    txMaxFee: BigNumberish;
    requestedAt: BigNumberish;
  };

  export type RedemptionRequestStructOutput = [
    redeemer: string,
    requestedAmount: bigint,
    treasuryFee: bigint,
    txMaxFee: bigint,
    requestedAt: bigint
  ] & {
    redeemer: string;
    requestedAmount: bigint;
    treasuryFee: bigint;
    txMaxFee: bigint;
    requestedAt: bigint;
  };

  export type WalletStruct = {
    ecdsaWalletID: BytesLike;
    mainUtxoHash: BytesLike;
    pendingRedemptionsValue: BigNumberish;
    createdAt: BigNumberish;
    movingFundsRequestedAt: BigNumberish;
    closingStartedAt: BigNumberish;
    state: BigNumberish;
  };

  export type WalletStructOutput = [
    ecdsaWalletID: string,
    mainUtxoHash: string,
    pendingRedemptionsValue: bigint,
    createdAt: bigint,
    movingFundsRequestedAt: bigint,
    closingStartedAt: bigint,
    state: bigint
  ] & {
    ecdsaWalletID: string;
    mainUtxoHash: string;
    pendingRedemptionsValue: bigint;
    createdAt: bigint;
    movingFundsRequestedAt: bigint;
    closingStartedAt: bigint;
    state: bigint;
  };
}

export interface BridgeStubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "__ecdsaWalletCreatedCallback"
      | "__ecdsaWalletHeartbeatFailedCallback"
      | "bank"
      | "calculateRedemptionKey"
      | "contractReferences"
      | "devRequestNewWallet"
      | "ecdsaWalletRegistry"
      | "getPendingRedemption"
      | "getRedemptionWatchtower"
      | "getWallet"
      | "pendingRedemptions"
      | "redemptionParameters"
      | "redemptionRequestMinAge"
      | "registerWallet"
      | "reimbursementPool"
      | "relay"
      | "requestNewWallet"
      | "requestRedemption"
      | "wallets"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RedemptionRequested"): EventFragment;

  encodeFunctionData(
    functionFragment: "__ecdsaWalletCreatedCallback",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "__ecdsaWalletHeartbeatFailedCallback",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "bank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculateRedemptionKey",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractReferences",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "devRequestNewWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ecdsaWalletRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRedemption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRedemptionWatchtower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWallet",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRedemptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionParameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redemptionRequestMinAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerWallet",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reimbursementPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "relay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestNewWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRedemption",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "wallets", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "__ecdsaWalletCreatedCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__ecdsaWalletHeartbeatFailedCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bank", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateRedemptionKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractReferences",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "devRequestNewWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ecdsaWalletRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedemptionWatchtower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingRedemptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redemptionRequestMinAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reimbursementPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestNewWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRedemption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wallets", data: BytesLike): Result;
}

export namespace RedemptionRequestedEvent {
  export type InputTuple = [
    walletPubKeyHash: BytesLike,
    redeemerOutputScript: BytesLike,
    redeemer: AddressLike,
    requestedAmount: BigNumberish,
    treasuryFee: BigNumberish,
    txMaxFee: BigNumberish
  ];
  export type OutputTuple = [
    walletPubKeyHash: string,
    redeemerOutputScript: string,
    redeemer: string,
    requestedAmount: bigint,
    treasuryFee: bigint,
    txMaxFee: bigint
  ];
  export interface OutputObject {
    walletPubKeyHash: string;
    redeemerOutputScript: string;
    redeemer: string;
    requestedAmount: bigint;
    treasuryFee: bigint;
    txMaxFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeStub extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeStub;
  waitForDeployment(): Promise<this>;

  interface: BridgeStubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  __ecdsaWalletCreatedCallback: TypedContractMethod<
    [walletID: BytesLike, publicKeyX: BytesLike, publicKeyY: BytesLike],
    [void],
    "nonpayable"
  >;

  __ecdsaWalletHeartbeatFailedCallback: TypedContractMethod<
    [walletID: BytesLike, publicKeyX: BytesLike, publicKeyY: BytesLike],
    [void],
    "nonpayable"
  >;

  bank: TypedContractMethod<[], [string], "view">;

  calculateRedemptionKey: TypedContractMethod<
    [walletPubKeyHash: BytesLike, redeemerOutputScript: BytesLike],
    [bigint],
    "view"
  >;

  contractReferences: TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        _bank: string;
        _relay: string;
        _ecdsaWalletRegistry: string;
        _reimbursementPool: string;
      }
    ],
    "view"
  >;

  devRequestNewWallet: TypedContractMethod<[], [void], "nonpayable">;

  ecdsaWalletRegistry: TypedContractMethod<[], [string], "view">;

  getPendingRedemption: TypedContractMethod<
    [redemptionKey: BigNumberish],
    [BridgeStub.RedemptionRequestStructOutput],
    "view"
  >;

  getRedemptionWatchtower: TypedContractMethod<[], [string], "view">;

  getWallet: TypedContractMethod<
    [walletPubKeyHash: BytesLike],
    [BridgeStub.WalletStructOutput],
    "view"
  >;

  pendingRedemptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        redeemer: string;
        requestedAmount: bigint;
        treasuryFee: bigint;
        txMaxFee: bigint;
        requestedAt: bigint;
      }
    ],
    "view"
  >;

  redemptionParameters: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        redemptionDustThreshold: bigint;
        redemptionTreasuryFeeDivisor: bigint;
        redemptionTxMaxFee: bigint;
        redemptionTxMaxTotalFee: bigint;
        redemptionTimeout: bigint;
        redemptionTimeoutSlashingAmount: bigint;
        redemptionTimeoutNotifierRewardMultiplier: bigint;
      }
    ],
    "view"
  >;

  redemptionRequestMinAge: TypedContractMethod<[], [bigint], "view">;

  registerWallet: TypedContractMethod<
    [walletPubKeyHash: BytesLike, ecdsaWalletID: BytesLike],
    [void],
    "nonpayable"
  >;

  reimbursementPool: TypedContractMethod<[], [string], "view">;

  relay: TypedContractMethod<[], [string], "view">;

  requestNewWallet: TypedContractMethod<[], [void], "nonpayable">;

  requestRedemption: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      redeemerOutputScript: BytesLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  wallets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        ecdsaWalletID: string;
        mainUtxoHash: string;
        pendingRedemptionsValue: bigint;
        createdAt: bigint;
        movingFundsRequestedAt: bigint;
        closingStartedAt: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "__ecdsaWalletCreatedCallback"
  ): TypedContractMethod<
    [walletID: BytesLike, publicKeyX: BytesLike, publicKeyY: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "__ecdsaWalletHeartbeatFailedCallback"
  ): TypedContractMethod<
    [walletID: BytesLike, publicKeyX: BytesLike, publicKeyY: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bank"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateRedemptionKey"
  ): TypedContractMethod<
    [walletPubKeyHash: BytesLike, redeemerOutputScript: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "contractReferences"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string] & {
        _bank: string;
        _relay: string;
        _ecdsaWalletRegistry: string;
        _reimbursementPool: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "devRequestNewWallet"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ecdsaWalletRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPendingRedemption"
  ): TypedContractMethod<
    [redemptionKey: BigNumberish],
    [BridgeStub.RedemptionRequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRedemptionWatchtower"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getWallet"
  ): TypedContractMethod<
    [walletPubKeyHash: BytesLike],
    [BridgeStub.WalletStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRedemptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        redeemer: string;
        requestedAmount: bigint;
        treasuryFee: bigint;
        txMaxFee: bigint;
        requestedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "redemptionParameters"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        redemptionDustThreshold: bigint;
        redemptionTreasuryFeeDivisor: bigint;
        redemptionTxMaxFee: bigint;
        redemptionTxMaxTotalFee: bigint;
        redemptionTimeout: bigint;
        redemptionTimeoutSlashingAmount: bigint;
        redemptionTimeoutNotifierRewardMultiplier: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "redemptionRequestMinAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerWallet"
  ): TypedContractMethod<
    [walletPubKeyHash: BytesLike, ecdsaWalletID: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reimbursementPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relay"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestNewWallet"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRedemption"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      redeemerOutputScript: BytesLike,
      amount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wallets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        ecdsaWalletID: string;
        mainUtxoHash: string;
        pendingRedemptionsValue: bigint;
        createdAt: bigint;
        movingFundsRequestedAt: bigint;
        closingStartedAt: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RedemptionRequested"
  ): TypedContractEvent<
    RedemptionRequestedEvent.InputTuple,
    RedemptionRequestedEvent.OutputTuple,
    RedemptionRequestedEvent.OutputObject
  >;

  filters: {
    "RedemptionRequested(bytes20,bytes,address,uint64,uint64,uint64)": TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;
    RedemptionRequested: TypedContractEvent<
      RedemptionRequestedEvent.InputTuple,
      RedemptionRequestedEvent.OutputTuple,
      RedemptionRequestedEvent.OutputObject
    >;
  };
}
