/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bridgeStubSol from "./BridgeStub.sol";
export type { bridgeStubSol };
export type { WalletProposalValidatorStub } from "./WalletProposalValidatorStub";
export * as factories from "./factories";
export type { BridgeStub } from "./BridgeStub.sol/BridgeStub";
export { BridgeStub__factory } from "./factories/BridgeStub.sol/BridgeStub__factory";
export type { IWalletRegistry } from "./BridgeStub.sol/IWalletRegistry";
export { IWalletRegistry__factory } from "./factories/BridgeStub.sol/IWalletRegistry__factory";
export { WalletProposalValidatorStub__factory } from "./factories/WalletProposalValidatorStub__factory";
