/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface WalletProposalValidatorStubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEPOSIT_MIN_AGE"
      | "DEPOSIT_REFUND_SAFETY_MARGIN"
      | "DEPOSIT_SWEEP_MAX_SIZE"
      | "REDEMPTION_MAX_SIZE"
      | "REDEMPTION_REQUEST_MIN_AGE"
      | "REDEMPTION_REQUEST_TIMEOUT_SAFETY_MARGIN"
      | "bridge"
      | "validateDepositSweepProposal"
      | "validateHeartbeatProposal"
      | "validateMovedFundsSweepProposal"
      | "validateMovingFundsProposal"
      | "validateRedemptionProposal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DEPOSIT_MIN_AGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_REFUND_SAFETY_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEPOSIT_SWEEP_MAX_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REDEMPTION_MAX_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REDEMPTION_REQUEST_MIN_AGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REDEMPTION_REQUEST_TIMEOUT_SAFETY_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateDepositSweepProposal",
    values: [BytesLike, BytesLike[], BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateHeartbeatProposal",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateMovedFundsSweepProposal",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateMovingFundsProposal",
    values: [
      BytesLike,
      BytesLike[],
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateRedemptionProposal",
    values: [BytesLike, BytesLike[], BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEPOSIT_MIN_AGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_REFUND_SAFETY_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEPOSIT_SWEEP_MAX_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REDEMPTION_MAX_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REDEMPTION_REQUEST_MIN_AGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REDEMPTION_REQUEST_TIMEOUT_SAFETY_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateDepositSweepProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateHeartbeatProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateMovedFundsSweepProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateMovingFundsProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateRedemptionProposal",
    data: BytesLike
  ): Result;
}

export interface WalletProposalValidatorStub extends BaseContract {
  connect(runner?: ContractRunner | null): WalletProposalValidatorStub;
  waitForDeployment(): Promise<this>;

  interface: WalletProposalValidatorStubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEPOSIT_MIN_AGE: TypedContractMethod<[], [bigint], "view">;

  DEPOSIT_REFUND_SAFETY_MARGIN: TypedContractMethod<[], [bigint], "view">;

  DEPOSIT_SWEEP_MAX_SIZE: TypedContractMethod<[], [bigint], "view">;

  REDEMPTION_MAX_SIZE: TypedContractMethod<[], [bigint], "view">;

  REDEMPTION_REQUEST_MIN_AGE: TypedContractMethod<[], [bigint], "view">;

  REDEMPTION_REQUEST_TIMEOUT_SAFETY_MARGIN: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  bridge: TypedContractMethod<[], [string], "view">;

  validateDepositSweepProposal: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      depositsPubKeys: BytesLike[],
      sweepTxFee: BigNumberish,
      depositsRevealBlocks: BigNumberish,
      depositsExtraInfo: BytesLike
    ],
    [boolean],
    "view"
  >;

  validateHeartbeatProposal: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      heartbeatTxHash: BytesLike,
      heartbeatTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;

  validateMovedFundsSweepProposal: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      movingFundsTxHash: BytesLike,
      movingFundsTxOutputIndex: BigNumberish,
      sweepTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;

  validateMovingFundsProposal: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      targetWallets: BytesLike[],
      movingFundsTxFee: BigNumberish,
      mainUtxoHash: BytesLike,
      mainUtxoOutputIndex: BigNumberish,
      mainUtxoValue: BigNumberish
    ],
    [boolean],
    "view"
  >;

  validateRedemptionProposal: TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      redeemersOutputScripts: BytesLike[],
      redemptionTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEPOSIT_MIN_AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_REFUND_SAFETY_MARGIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEPOSIT_SWEEP_MAX_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REDEMPTION_MAX_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REDEMPTION_REQUEST_MIN_AGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REDEMPTION_REQUEST_TIMEOUT_SAFETY_MARGIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateDepositSweepProposal"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      depositsPubKeys: BytesLike[],
      sweepTxFee: BigNumberish,
      depositsRevealBlocks: BigNumberish,
      depositsExtraInfo: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateHeartbeatProposal"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      heartbeatTxHash: BytesLike,
      heartbeatTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateMovedFundsSweepProposal"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      movingFundsTxHash: BytesLike,
      movingFundsTxOutputIndex: BigNumberish,
      sweepTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateMovingFundsProposal"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      targetWallets: BytesLike[],
      movingFundsTxFee: BigNumberish,
      mainUtxoHash: BytesLike,
      mainUtxoOutputIndex: BigNumberish,
      mainUtxoValue: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "validateRedemptionProposal"
  ): TypedContractMethod<
    [
      walletPubKeyHash: BytesLike,
      redeemersOutputScripts: BytesLike[],
      redemptionTxFee: BigNumberish
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
