/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bridgeStubSol from "./BridgeStub.sol";
export { WalletProposalValidatorStub__factory } from "./WalletProposalValidatorStub__factory";
