/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWalletRegistry,
  IWalletRegistryInterface,
} from "../IWalletRegistry";

const _abi = [
  {
    inputs: [],
    name: "requestNewWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWalletRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IWalletRegistryInterface {
    return new Interface(_abi) as IWalletRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWalletRegistry {
    return new Contract(address, _abi, runner) as unknown as IWalletRegistry;
  }
}
